// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRgZu5ve-d2cyuhM3NleQ660iWh53CS-o',
    appId: '1:1041375918708:web:0ed645c0cda844606eef21',
    messagingSenderId: '1041375918708',
    projectId: 'reddit-tutorial-e8f61',
    authDomain: 'reddit-tutorial-e8f61.firebaseapp.com',
    storageBucket: 'reddit-tutorial-e8f61.appspot.com',
    measurementId: 'G-S078GJWT1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaBxJnvjdKeU3WgyzvesGqIixUycLCr04',
    appId: '1:1041375918708:android:799deb15c90114b36eef21',
    messagingSenderId: '1041375918708',
    projectId: 'reddit-tutorial-e8f61',
    storageBucket: 'reddit-tutorial-e8f61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZnCWiusNnR9EfnttVuegL-0sG_0CImHA',
    appId: '1:1041375918708:ios:afc1dcbaf662df8f6eef21',
    messagingSenderId: '1041375918708',
    projectId: 'reddit-tutorial-e8f61',
    storageBucket: 'reddit-tutorial-e8f61.appspot.com',
    iosClientId: '1041375918708-9736n5964ap62ddm0p7qt8mgria99b7n.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditTutorial',
  );
}
